overrides:
  vite@>=3.0.0 <=3.2.7: '>=3.2.8'
  vite@>=3.0.0 <=3.2.8: '>=3.2.10'
  dompurify@<2.5.4: '>=2.5.4'
  vite@<3.2.11: '>=3.2.11'
  vite@<=3.2.10: '>=3.2.11'
  dompurify@<2.5.0: '>=2.5.0'
  dompurify@<2.4.2: '>=2.4.2'
  '@octokit/request-error@>=1.0.0 <5.1.1': '>=5.1.1'
  esbuild@<=0.24.2: '>=0.25.0'
  vite@<=4.5.5: '>=4.5.6'
  '@octokit/request@>=1.0.0 <8.4.1': '>=8.4.1'
  '@octokit/plugin-paginate-rest@>=1.0.0 <9.2.2': '>=9.2.2'
  vite@<4.5.10: '>=4.5.10'
  vite@<4.5.11: '>=4.5.11'
  vite@<4.5.13: '>=4.5.13'
  vite@<=4.5.13: '>=4.5.14'
  vite@<4.5.12: '>=4.5.12'
  dompurify@<3.2.4: '>=3.2.4'
